version: "3"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: flip_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass_123
    command: ["--bind_ip_all", "--port", "27017", "--auth"]
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-config:/data/configdb
      - ./key/mongodb-keyfile:/etc/mongo/mongodb-keyfile

